### ISSUE TITLE
Split choice_to_option

### ISSUE THREAD

**Issue by boxed** [TriOptima/iommi#101]
`choice_to_option` returns a 4-tuple which is very hard to work with. It would be better if it was split into multiple functions. Maybe

- choice_id_formatter
- choice_display_name_formatter

We could also consider having `ChoiceField`/`ChoiceColumn`/`ChoiceFilter` be a thing so that the base classes aren't cluttered by the features that aren't useful in the general case. The shortcuts would be on `Field`/`Column`/`Filter` still though.

**Comment by bgrundmann** [comment]
Furthermore `choice` should work out of the box with TextChoices and or Enum instances, with minimal work.  Or if `choice` directly can't then we should add appropriate additional shortcuts.
