### ISSUE TITLE
Strange lines in Field

### ISSUE THREAD

**Issue by bgrundmann** [TriOptima/iommi#133]
This part of the code of Field:

https://github.com/TriOptima/iommi/blob/84c2cf220fd4549a7bedc028605557c6d031dc37/iommi/form.py#L718-L724

seems to be a copy of sorts of these lines in Query:

https://github.com/TriOptima/iommi/blob/84c2cf220fd4549a7bedc028605557c6d031dc37/iommi/query.py#L260-L266

And indeed `self.search_fields` does not seem to be used in Field anywhere else.  Bad case of copy paste?

**Comment by boxed** [comment]
`search_fields` is used by `choice_queryset__extra__filter_and_sort`

**Comment by bgrundmann** [comment]
Doh. Missed that.  Still sad at the code duplication.  We are missing some abstraction I guess.  Also I still dislike iommi using the extra namespace.  Or more precisely I dislike the whole extra namespace ...
