### ISSUE TITLE
Rename `attr`

### ISSUE THREAD

**Issue by boxed** [TriOptima/iommi#235]
`attr` is rarely used, while `attrs` is used often. A big percentage of the times I write `attr` I actually meant `attrs`. These names should be more different. `attribute` for example. (Django models uses `attname` but I think that's bad)

**Comment by ritiksoni00** [comment]
in the project, we just need to rename `attr` to `attrs` ?

**Comment by boxed** [comment]
No. Attr and attrs are very different things. But the names are quite similar, that's the problem.

**Comment by jlubcke** [comment]
This will never happen...
