### ISSUE TITLE
Is there a convenient way to adapt to Django Form Fields?

### ISSUE THREAD

**Issue by yanhuixie** [TriOptima/iommi#245]
For example, we are trying to add a captcha for the login form, by the django way we should use captcha.Fields.CaptchaField of the django-simple-captcha, it inherited from the django.Forms.Fields.MultiValueField, they achieved more complex logic. If we don't have a convenient way to adapt it, maybe we need to make a copy of a bunch of code, which is not very friendly. Any suggestions are appreciated, thank you.

```python
from django.contrib.auth.forms import AuthenticationForm
from captcha.fields import CaptchaField

class AuthAdminForm(AuthenticationForm):
    captcha = CaptchaField(label='Captcha')

```

**Comment by boxed** [comment]
I read the code of `CaptchaField`. It's a lot of code I agree. But it doesn't seem to do all that much. It looks like most of the code is to deal with Django forms being awkward to work with. Just starting from scratch and implementing a captcha field in iommi using the django-simple-capcha code (without the forms stuff) seems like a reasonable approach.

Another approach is to use the Django Form for just the login form. There's no need to convert everything to iommi initially. You can have some views using legacy tech...

**Comment by yanhuixie** [comment]
Thanks @boxed ! Your suggestion gave me a good inspiration. There's no need to use iommi for everything. We'll use iommi for the features that it suits, and django's forms and templates will do the rest.
