### ISSUE TITLE
Related field doesn't appear when using custom base template

### ISSUE THREAD

**Issue by Jocelyn-AGORO** [TriOptima/iommi#246]
Iommi is very great, I like it. When I was trying to add my custom base as specified in docs.related fields (foreignkey fields) doesn't appear. Ohh!!! Another problem, I don't know how to change the value of the create form button.I want it to be in french but I don't see the right parameter in docs.

**Comment by boxed** [comment]
Could you show some code of what you've tried?

As for French: it would be great if you could supply a French translation! We have German, Swedish, Chinese and of course English so far.

**Comment by Jocelyn-AGORO** [comment]
```
settings.py
IOMMI_DEFAULT_STYLE = Style(
    bootstrap,
    base_template=str(BASE_DIR)+'/dashboard/templates/base.html',
    root__assets=dict(
        my_project_custom_css=Asset.css(attrs__href='/static/custom.css'),
        my_project_custom_js=Asset.js(attrs__src='/static/custom.js'),
    ),
)

views.py

def conducteurs(request):
    conducteur_form = Form.create(
        auto__model=Conducteur,
        auto__exclude=['created_at', 'updated_at'],
        h_tag=html.h1('Ajouter un nouveau Conducteur'),
        fields__nom__input__attrs__placeholder='Nom ...').bind(request=request)
    conducteur_table = Table(auto__model=Conducteur).bind(request=request)
    return render(request, 'iommi.html', {
        'conducteur_form': conducteur_form,
        'conducteur_table': conducteur_table,
        'name': 'conducteurs'
    })
```
![Capture d’écran (16)](https://user-images.githubusercontent.com/61328035/155841062-44a3bd22-b5d7-4e98-ab02-72120ef99ca0.png)

**nothing in the dropdown for company field**

![Capture d’écran (18)](https://user-images.githubusercontent.com/61328035/155841072-2b3e5ea4-ac73-4fd7-b3b4-1f22ecb911a0.png)

**Comment by boxed** [comment]
Ah, I think you aren't using iommi to the fullest. So technically what you're missing is https://docs.iommi.rocks/en/latest/legacy_fbv.html#ajax-dispatch but you shouldn't do this in your case. You can simplify to remove the need for this!

```py
def conducteurs(request):
    class ConducteurPage(Page):
        conducteur_form = Form.create(
            auto__model=Conducteur,
            auto__exclude=['created_at', 'updated_at'],
            h_tag=html.h1('Ajouter un nouveau Conducteur'),
            fields__nom__input__attrs__placeholder='Nom ...')
            
        conducteur_table = Table(auto__model=Conducteur)
    
    return ConducteurPage()
```

There's something strange with the `iommi.html` render part here. You shouldn't need that file at all.

**Comment by Jocelyn-AGORO** [comment]
Oh before I forget, just a proposal for custom style. I think it is better to take a string as class attrs
for a specific field, for example if class attribute is "class = 'rounded-pill  text-center my-2' " then we pass the value  'rounded-pill  text-center my-2' to fields__field_name__input__class_attrs.
It should look like this

```python
form = Form.create(
auto__model=Model,
fields__field_name__input__class__attrs='rounded-pill  text-center my-2'
)
```
I try something but it doesn't exactly that :

```python
classes= 'rounded-pill  text-center my-2'
classes={ class_:  True for class_ in classes.split() }
```
Now I can make this  :
```python
form = Form.create(
auto__model=Model,
fields__field_name__input__class__attrs=classes
)
```

**Comment by boxed** [comment]
> Thanks for reply but I need to add ConducteurForm and ConducteurTable as Fragment on my page because there are many others components on my page.

I think you want to define your style (or *a* style) to include all those other components.

**Comment by boxed** [comment]
> Oh before I forget, just a proposal for custom style. I think it is better to take a string as class attrs
for a specific field

We used to have that. It was a total mess as things scaled up. You couldn't compose stuff so if you had a string type class list you can't turn off a specific class later.

**Comment by boxed** [comment]
I closed this because we didn't get any feedback on it for a long time.

If you want more help on this you could reopen this, but it might be better to jump into the discord server for help more interactively.
