### ISSUE TITLE
[BUG] AttributeError: 'LiveEditPage' object has no attribute 'status_code'

### ISSUE THREAD

**Issue by patrickcurl** [TriOptima/iommi#292]
Just installed this, and I opened the library folder and found two ways of fixing this. 

1. add status_code=200 to Page class.
2. add status_code=200 to LiveEditPage in place of "pass"

After that the live-editing pages worked like a charm. I didn't look too far into the internals, there may be a better more sensible way to do this, or cover bases here, or add try/catch somewhere but I was going for quickest hack just to get it working.

**Comment by patrickcurl** [comment]
Edit: just adding status_code = None works too.. 

```python
# This class exists just to provide a way to style the page
class LiveEditPage(Page):
    status_code = None
```

**Comment by boxed** [comment]
What is the code of the thing you are trying to live edit?

**Comment by jlubcke** [comment]
This is most likely due to some other middleware seeing the iommi object before the iommi middleware makes a HttpResponse out of it. 
Please re-open this ticket with example code (and maybe the list of configured middlewares) if this is still an issue.
