### ISSUE TITLE
Unable to modify default style 

### ISSUE THREAD

**Issue by friedgit** [TriOptima/iommi#293]
Hi

This is probably more of a request for help and clarification than a genuine issue. (However it has become a bit of an issue for me and I don't know where else to ask.)

I am attempting to produce a css style based on the shipped default 'semantic ui', which I have chosen because it has visible vertical as well as horizontal borders, but with centred instead of left adjusted text. 

I can confirm that my_style  has been successfully registered and is recognised by setting IOMMI_DEFAULT_STYLE = 'my_style' in settings.py, because if I change the base style to bootstrap or base I can see the different renderings that result. However my attempts to centre the text are silently ignored. I have limited experience with css, html and javascript syntax by the way, which is part of the reason why I found iommi such an attractive framework to work with, but maybe this accounts for the silent failure. AppConfig attached.
[apps.py.txt](https://github.com/TriOptima/iommi/files/9269067/apps.py.txt)

Regards and thanks
David Wallace

**Comment by friedgit** [comment]
Just corrected the spelling of 'center' but that does't help me.
[apps.py.txt](https://github.com/TriOptima/iommi/files/9269184/apps.py.txt)

**Comment by friedgit** [comment]
doesn't help me

**Comment by boxed** [comment]
First let's do this:

```py
from django.apps import AppConfig
from iommi import Style, register_style, Asset
from iommi.style_semantic_ui import semantic_ui
from iommi.style_bootstrap import bootstrap
from iommi.style_base import base


my_style =   Style(semantic_ui, 
    root_assets__event_css = Asset.css({'css-style: "text-align: centre"'})
)


class EventsConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'events'
    def ready(self):
        register_style('my_style', my_style)
```

Ok, so what are you trying to center? The `{'css-style: "text-align: centre"'}` part doesn't make sense to me.

**Comment by friedgit** [comment]
Hi Anders

Thanks for responding so promptly to this. I am trying to center the text in all cells of any table displayed. 
I have no idea at all if this is the right way to approach this.

I have done as you suggest and used a ready function, but first had to change my_style to EventsConfig.my_style to get past the pre-compile stage. I verified my_style was still being activated by changing semantic_ui to bootstrap and back again, but none of the 4 root_assets assignments above had any effect. The page still displayed in each case, but with the contents of all the cells always aligned left as seems to be the default.

Thanks
David

```from django.apps import AppConfig
from iommi import Style, register_style, Asset
from iommi.style_semantic_ui import semantic_ui
from iommi.style_bootstrap import bootstrap
from iommi.style_base import base


class EventsConfig(AppConfig):
   default_auto_field = 'django.db.models.BigAutoField'
   name = 'events'
   my_style =   Style(semantic_ui, 
                     # root_assets__event_css = Asset.css({'css-style: "text-align: center"'})
                     # root_assets__event_css = Asset.css({'css: "text-align: center"'})
                     # root_assets__event_css = Asset.css({'td: "text-align: center"'})
                     root_assets__event_css = Asset.css({'td-style: "text-align: center"'})
                     )
   def ready(self):
      register_style('my_style', EventsConfig.my_style)```

**Comment by friedgit** [comment]
assignments below not above

**Comment by boxed** [comment]
What you normally want to do is add a CSS file to your project, and then link to it in your style like `Asset.css(attrs__href='/static/custom.css')`, then in that css file write your CSS rules. In your case something like
```css
table td {
    text-align: center;
}
```

**Comment by friedgit** [comment]
I made a copy of your suggested css file content above, and put it in a file called center.css a directory called static, which I placed  at the same directory tree level as manage.py I changed my apps.py as follows. All of the following displayed the page, but without any centering of cell text:
1. Applying the first root_assets assignment only (as shown)
2. Applying the second root_assets assignment only, specifying a non-existent file
3. Commenting both of those lines out and not applying any root_assets assignment at all.
```from django.apps import AppConfig
from iommi import Style, register_style, Asset
from iommi.style_semantic_ui import semantic_ui
from iommi.style_bootstrap import bootstrap
from iommi.style_base import base


class EventsConfig(AppConfig):
   default_auto_field = 'django.db.models.BigAutoField'
   name = 'events'
   my_style =   Style(semantic_ui, 
                     root_assets__event_css = Asset.css(attrs__href = '/static/center.css')
                     # root_assets__event_css = Asset.css(attrs__href = '/static/NOTcenter.css')
                     )
   def ready(self):
      register_style('my_style', EventsConfig.my_style)```

**Comment by friedgit** [comment]
I am clearly missing something elementary here, but can I suggest that a complete self contained demonstration project of this simple use case - centered text in tables rather than left-aligned - would be a really valuable addition to the iommi documentation.

**Comment by boxed** [comment]
The problem you're having now is that you don't understand how static files works in django. I recommend looking at the django docs for that.

**Comment by friedgit** [comment]
I am not sure that I properly understand static files in django even now, but I managed to get it to work with the help of this article written by Will Vincent: https://learndjango.com/tutorials/django-static-files.


Contents of `apps.py` :
```
from django.apps import AppConfig
from iommi import Style, register_style, Asset
from iommi.style_bootstrap import bootstrap


class EventsConfig(AppConfig):
   default_auto_field = 'django.db.models.BigAutoField'
   name = 'events'
   my_style =   Style( 
                     bootstrap,
                     root__assets__events_css = Asset.css(attrs__href = '/static/base.css')
                     )
   def ready(self):
      register_style('my_style', EventsConfig.my_style)
```

At the same level as manage.py, I created a directory `static` and put into it my css file, now called `base.css`  with the same content as before:
```
table td {
  text-align: center;
}
``` 

In `settings.py` I have these declarations:
```

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
```

The above seems to be effective. Not sure what was wrong before - maybe I previously had the css file in the wrong location, or the wrong declarations in `settings.py`. Thanks for your time and advice.

**Comment by friedgit** [comment]
I have found out a crucial difference, although I don't think it was the only error I made. In the non-working attempt, in `apps.py` I had:
```
root_assets__event_css = Asset.css(attrs__href = '/static/center.css')
```
But if I change it to this, with the dunder between `root` and `assets`, it works:
```
root__assets__event_css = Asset.css(attrs__href = '/static/center.css')
```
This is a parameter supplied to `Style` which is a class imported from iommi. Is it feasible for iommi to do a sanity check on the parameters for instances of `Style`? I have `DEBUG = True` in `settings.py` but the failure is silent in the non-working case.

**Comment by friedgit** [comment]
I do get an extra line of debug in the working case:
```
[20/Aug/2022 22:18:09] "GET /static/center.css HTTP/1.1" 304 0
```
which does not appear in the failure case, so there **is** a difference. But if one is not looking for that extra line of console output, then one doesn't recognize the significance of its absence - the console debug output is just the same as if no static files were used.

**Comment by boxed** [comment]
> Is it feasible for iommi to do a sanity check on the parameters for instances of Style?

We do check most things, but in this case you happen to get into a case where iommi thinks you're trying to add some config to a class called `root_assets` which is obviously wrong to a human eye, but not to a program. 

I guess we could check if you try to style something not starting with a capital letter and disallow that, but it seems a bit heavy handed... what do you think @jlubcke ?

**Comment by jlubcke** [comment]
At least it should be possible to make a test-case for a given Style to verify that the class references resolves to something.

**Comment by boxed** [comment]
Can we? The class names aren't fully qualified, so it seems it'd be quite weird and complex to try to find if a class exists...

**Comment by jlubcke** [comment]
Ah, right. No we can't :(

**Comment by friedgit** [comment]
Could there be a concept of reserved words, like `root` and `assets`, and maybe others, so that when a class name seems to consist  **only** of these reserved words and separators then a warning is issued like `You have specified a class called root_assets. Did you mean root__assets?`. But allow something like `root1234_assets` through as intentional.

**Comment by boxed** [comment]
Yea we could do that. I think I like the idea of the big hammer of warning on anything not starting with a capital letter though. In that warning we could be smart and say "did you mean...?" or something.

**Comment by friedgit** [comment]
That would work just as well in my case at least, and seems simpler to do

**Comment by boxed** [comment]
I get a big confused reading through this ticket heh, but I guess it was solved? I'm closing this, and if you think it was closed in error please tell me and reopen it.

**Comment by friedgit** [comment]
Confirming the fix because there is no longer a silent failure. Using iommi 5.3.0 I now get the following warning message when I re-introduce the typo (single underscore: root_assets instead of dunder: root__assets)

C:\Users\david\OneDrive\Documents\ksail2\ksail2_root\events\apps.py changed, reloading.
C:\Users\david\OneDrive\Documents\ksail2\env_ksail2\lib\site-packages\iommi\style.py:84: UserWarning: Style definition got the keyword root_assets which starts with a lowercase letter. Classes should start with an uppercase letter. Either you made a mistake in passing something that won't match any config, or you should rename your class to start with a capital letter.
  warnings.warn(f"Style definition got the keyword {k} which starts with a lowercase letter. Classes should start with an uppercase letter. Either you made a mistake in passing something that won't match any config, or you should rename your class to start with a capital letter.")

However while this warning tells me something is probably wrong, it doesn't trace back to the line in **my** source code or even the file in my source code where the warning is triggered. Do you think it should? Also, assuming that I had been able to identify which of my files is the source of the error, I might have been tempted, if I saw this warning for the first time, to attempt a "correction" by changing "root_assets" to "Root_assets"!

**Comment by boxed** [comment]
I think it's pretty ok like that. If you need to find the source you can set a breakpoint, and freetext search your code base for the string. In you case `root_assets` should only match one place in the code base.

> I might have been tempted, if I saw this warning for the first time, to attempt a "correction" by changing "root_assets" to "Root_assets"!

hmm.. well we can't really do anything about that. If a user solves problems with the attitude of not understanding and just trying to silence warnings with no care about if it solves any problems, that's another much deeper problem.

Again, we can't, at style definition time, know all the valid class names. I am open to ideas of how to make this even better though.
