### ISSUE TITLE
`subtitle` not supported like `title`

### ISSUE THREAD

**Issue by friedgit** [TriOptima/iommi#298]
I want to display a table with a subtitle as well as a title, but I find that I cannot do this directly as the class Table doesn't have an refinable attribute called subtitle, only a title. So instead I include the table (stripped of its original title) in a page, below the page's title and subtitle. This item in the documentation [https://docs.iommi.rocks/en/latest/cookbook_parts_pages.html#how-do-i-override-part-of-a-part-page](https://docs.iommi.rocks/en/latest/cookbook_parts_pages.html#how-do-i-override-part-of-a-part-page) shows me how I can add a subtitle as well as a title to a page, and over-ride both of them. But it seems to infer that both subtitle and title are treated in an equivalent way, whereas I have found that they're not. In the snippet below I found two working methods of introducing a subtitle - method A is the documented way, and method B I stumbled upon myself. Method B is probably inferior because it mixes the style h2 with the content, but it avoids the (to me mysterious) `children__child` construct. In both methods I found

- You do not need to declare the `title` in the class because it is already there by default, at the top of the page in the desired h1 style. You just need to assign it a value, which can be done in the response to the request, and must be done there, because it depends on a parameter of the request.

- You **do** need to declare the `subtitle` in the class, above where you declare the table, because if you don't, it will appear on the page underneath the table instead of above it. This applies to both method A, where the class declaration also sets the h2 style, and method B, where the class declaration is only there to establish the position of the subtitle on the page. It automatically appears below the `title`, which, as stated, does not need to be declared in the class.

So, is the treatment of `subtitle` as a second-class citizen compared to `title` intentional and actually desirable for flexibility, and if this is so, could this be made clearer in the documentation? And would you say method A is to be recommended over method B, or vice-versa, or either is ok?
```py
class MyPage(Page):

  # subtitle = ''           # Method B: sets the position of member `subtitle` above the table, but not the h2 style
  subtitle = html.h2('')    # Method A: sets the position of member `subtitle` above the table incorporating h2 style
  my_table = ScheduleTable()  


def schedule_view(request, id):

  return MyPage(

    title = f'Table {id:02d}', 
    # parts__subtitle = html.h2(f'For schedule {id:01d}'),          # Method B: refers to `subtitle`` in MyPage and sets the h2 style
    parts__subtitle__children__child = f'For schedule {id:01d}',    # Method A: refers to `subtitle`` in MyPage and is able to inherit the h2 style
    parts__my_table__rows = TeamTemplate.objects.filter(schedule__pk = id),
  )
```

**Comment by boxed** [comment]
I've discussed this a bit with @jlubcke and I think this actually shows a bit of a design flaw with Table. We have an idea how to fix this, that we will hopefully look at in the coming week. 

Until then I think I'd do this:

```py
class SomePage(Page):
    subtitle = html.h2('subtitle')
    table = SomeTable()
    class Meta:
        title = 'Title'
```
Which is strictly speaking a bit wrong, as the auto-header level stuff won't properly work with it, but it should work fine for your use case.

**Comment by friedgit** [comment]
Unless I am mistaken, the difference between my use-case and your suggestion is that I have an extra parameter `id` whose value is only known when a request is made, and so I don't think the value of `subtitle` (in your example) can be assigned in the class declaration in mine. Instead I have the f-string `f'For schedule {id:01d}'`, which as I understand, can only be assigned dynamically in the view. (It's an artificial example, because I use the same `id`,  in a redundant kind of way, to construct the `title`, but in real life I actually do want to pass a parameter used exclusively to construct the `subtitle`)

**Comment by boxed** [comment]
You can do late evaluation though. Or even use templates. As long as you can get to the data from the request object you should be good.

**Comment by friedgit** [comment]
I think that's what I did in my original post (?) in both methods A and B. They both work btw. I just wanted to show how much easier it is to do it with a title (which as you point out, can be applied directly to Table) rather than a subtitle.

**Comment by boxed** [comment]
Ah. Yea, then I agree.

**Comment by boxed** [comment]
iommi 5.2.0 is released that enabled you to insert arbitrary stuff in the table. So now you can do this:

```py
Table(auto__model=Foo, title='Some title', outer__subtitle=html.h2('Subtitle here', after='h_tag')
```

**Comment by friedgit** [comment]
Not working for me in iommi 5.3.0, maybe because I need to set the subtitle dynamically instead of declaring it in the class?

```
def flight_view(request, event_id, stage_number):
  
  event_stage = Stage.objects.get(event = EventStage.get_event(request), stage_number=stage_number)
  event_stage_schedule_num = event_stage.schedule.pk

  return FlightTable(
    title = Event.objects.get(pk = event_id).name,
    # outer__subtitle = f'Stage {stage_number:01d}', # dynamically resolved at request time - what I require
    # outer__subtitle = html.h2('xyz', after='h_tag'), # fixed test try 1 - fails
    outer__subtitle = 'xyz', # simpler fixed text try 2 - also fails
    rows = TeamTemplate.objects.filter(schedule = event_stage_schedule_num),
  )
```
I get this error:
```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/flight/1/1/

Django Version: 3.2.14
Python Version: 3.10.4
Installed Applications:
['events.apps.EventsConfig',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'iommi']
Installed Middleware:
['iommi.live_edit.Middleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'iommi.sql_trace.Middleware',
 'iommi.profiling.Middleware',
 'iommi.middleware']



Traceback (most recent call last):
  File "C:\Users\david\OneDrive\Documents\ksail2\ksail2_root\events\views.py", line 120, in <iommi declaration>
    return FlightTable(

The above exception () was the direct cause of the following exception:
  File "C:\Users\david\OneDrive\Documents\ksail2\env_ksail2\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\david\OneDrive\Documents\ksail2\env_ksail2\lib\site-packages\iommi\__init__.py", line 90, in iommi_middleware
    return render_if_needed(request, get_response(request))
  File "C:\Users\david\OneDrive\Documents\ksail2\env_ksail2\lib\site-packages\iommi\__init__.py", line 73, in render_if_needed
    raise e from fake
  File "C:\Users\david\OneDrive\Documents\ksail2\env_ksail2\lib\site-packages\iommi\__init__.py", line 63, in render_if_needed
    response = response.bind(request=request)
  File "C:\Users\david\OneDrive\Documents\ksail2\env_ksail2\lib\site-packages\iommi\part.py", line 110, in bind
    result = super(Part, self).bind(parent=parent, request=request)
  File "C:\Users\david\OneDrive\Documents\ksail2\env_ksail2\lib\site-packages\iommi\traversable.py", line 184, in bind
    result.on_bind()
  File "C:\Users\david\OneDrive\Documents\ksail2\env_ksail2\lib\site-packages\iommi\table.py", line 1831, in on_bind
    self.outer(_name='outer')
  File "C:\Users\david\OneDrive\Documents\ksail2\env_ksail2\lib\site-packages\iommi\declarative\namespace.py", line 118, in __call__
    return call_target(*args, **params)
  File "C:\Users\david\OneDrive\Documents\ksail2\env_ksail2\lib\site-packages\iommi\declarative\util.py", line 17, in argument_injector_wrapper
    __init__orig(self, *new_args, **new_kwargs)
  File "C:\Users\david\OneDrive\Documents\ksail2\env_ksail2\lib\site-packages\iommi\shortcut.py", line 32, in wrapper_for_with_defaults
    instance = __target__(*args, **kwargs)
  File "C:\Users\david\OneDrive\Documents\ksail2\env_ksail2\lib\site-packages\iommi\fragment.py", line 168, in __init__
    super().__init__(_collect_instantiated_at_info=False, **kwargs)
  File "C:\Users\david\OneDrive\Documents\ksail2\env_ksail2\lib\site-packages\iommi\shortcut.py", line 32, in wrapper_for_with_defaults
    instance = __target__(*args, **kwargs)
  File "C:\Users\david\OneDrive\Documents\ksail2\env_ksail2\lib\site-packages\iommi\part.py", line 85, in __init__
    super(Part, self).__init__(**kwargs)
  File "C:\Users\david\OneDrive\Documents\ksail2\env_ksail2\lib\site-packages\iommi\traversable.py", line 68, in __init__
    super().__init__(**kwargs)
  File "C:\Users\david\OneDrive\Documents\ksail2\env_ksail2\lib\site-packages\iommi\declarative\util.py", line 28, in init_hook_wrapper
    __init__orig(self, *args, **kwargs)
  File "C:\Users\david\OneDrive\Documents\ksail2\env_ksail2\lib\site-packages\iommi\declarative\dispatch.py", line 10, in dispatch_defaults_wrapper
    return f(*args, **Namespace(defaults, kwargs))
  File "C:\Users\david\OneDrive\Documents\ksail2\env_ksail2\lib\site-packages\iommi\refinable.py", line 171, in __init__
    raise TypeError(

Exception Type: TypeError at /flight/1/1/
Exception Value: Fragment object has no refinable attribute(s): "subtitle".
Available attributes:
    after
    assets
    attrs
    children
    endpoints
    extra
    extra_evaluated
    include
    iommi_style
    tag
    template
```

**Comment by friedgit** [comment]
It doesn't seem to like outer__subtitle  being assigned to anything. But the method I described originally of inserting the table inside a page is working fine for me, so I can continue to use that.

**Comment by boxed** [comment]
doh!

The example should have been:

```py
Table(
    auto__model=Foo,
    title='Some title', 
    outer__children__subtitle=html.h2('Subtitle here', after='h_tag')
)
```

**Comment by boxed** [comment]
For your dynamic case you might want:

```py
outer__children__subtitle = Fragment(after='h_tag', template=Template(f'Stage {{ stage_number }}')
```
or something along those lines..

**Comment by friedgit** [comment]
Confirming ok when I use this:
`outer__children__subtitle = html.h2(f'Stage {stage_number:01d}', after='h_tag')`

**Comment by boxed** [comment]
Great!
