### ISSUE TITLE
Translation Issue (German .mo file)

### ISSUE THREAD

**Issue by davidrzs** [TriOptima/iommi#328]
Setting localization to German correctly fetches 
```
msgid "create"
msgstr "anlegen"
```
however, when trying to query `Create` it returns `create`.
After some investigating I found that creating the .mo file myself and replacing yours in `iommi-5.4.0/iommi/locale/de/LC_MESSAGES/` fixes the issue. I suspect you need to rebuild the german .mo file.

**Comment by boxed** [comment]
Thanks for reporting this! I believe I've fixed this now. Please let me know if this is still broken in the next release :P
