### ISSUE TITLE
LoginRequiredMixin not working with iommi class Pages

### ISSUE THREAD

**Issue by casparfritzen** [TriOptima/iommi#361]
I am struggling since hours to get the LoginRequiredMixin to work with iommi Pages and Forms.

``` Python
class TestPage(LoginRequiredMixin, Page):
    create_form = Form.create(
        auto__model=EcoLabel,
        auto__exclude=["created_at", "updated_at", "created_by", "modified_by"],
    )
    a_table = Table(
        auto__model=EcoLabel,
        columns__created_by__filter__include=True,
        query_from_indexes=True,
        auto__exclude=["firmenwagen_proof", "papier_proof", "umsatz_proof"],
    )

    class Meta:
        title = "A test page!"
```

Am I doing some obvious thing wrong?

When I am not logged in, nothing happens. if I write my own form class, it works tho...

Thank you for helping <3

**Comment by boxed** [comment]
iommi classes aren't Django Class Based Views, so they can't be composed with their mixins. 

In your urls.py you can do `path('test/', login_required(TestPage().as_view())` for example.

**Comment by casparfritzen** [comment]
Thank you, that's awesome :)
