### ISSUE TITLE
Page.as_view() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by nikartom** [TriOptima/iommi#364]
I try make example from docs and i have problem with Page class: **Page.as_view() missing 1 required positional argument: 'self'**
```
class Project(models.Model):
    manager = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name="Сотрудник")
    address = models.ForeignKey(Address, on_delete=models.PROTECT, verbose_name="Адрес")
    url = models.URLField(verbose_name="Ссылка на презентацию")
    sq = models.DecimalField(max_digits=5, decimal_places=1, verbose_name="Общая площадь")
    rent_tax = models.PositiveIntegerField(verbose_name="Арендная ставка")
```
**Views**
```
class Projects(Page):
    project = Table(auto__model=Project)

    class Meta:
        title = 'Project page!'
```
**URLs**
`path('projects/', views.Projects.as_view()),`

**Comment by boxed** [comment]
`path('projects/', views.Projects().as_view()),` is the correct code. Notice the `()`after `Projects`.

If you find an error in the docs about this please open an issue. There shouldn't be one as all the code samples in the docs are run as far as I know.

**Comment by nikartom** [comment]
> `path('projects/', views.Projects().as_view()),` is the correct code. Notice the `()`after `Projects`.
> 
> If you find an error in the docs about this please open an issue. There shouldn't be one as all the code samples in the docs are run as far as I know.

My mistake, sorry. Thanks for the tip.

**Comment by boxed** [comment]
No problem. If you're not on the discord I recommend it for quick questions like this.
