### ISSUE TITLE
it may not be possible to change the paginator template

### ISSUE THREAD

**Issue by sicksid** [TriOptima/iommi#4]
thanks for your library, i decided to implement it for a project im working on and so far it has been great and very easy to use, except for changing the pagination template to a custom one that matches our designers mockup... 

here is a piece of code from `iommi.tables.Table#on_bind`
```
        if self.page_size and request and isinstance(self.rows, QuerySet) and self.paginator is not None:
            try:
                self.page_size = int(request.GET.get('page_size', self.page_size)) if request else self.page_size
            except ValueError:
                pass

            if isinstance(self.paginator.call_target, type) and issubclass(self.paginator.call_target, DjangoPaginator):
                django_paginator = self.paginator(self.rows, self.page_size)
            elif isinstance(self.paginator.call_target, DjangoPaginator):
                django_paginator = self.paginator
            else:
                assert isinstance(self.paginator, Namespace)
                django_paginator = DjangoPaginator(self.rows, self.page_size)
            self.paginator = Paginator(table=self, django_paginator=django_paginator)

            try:
                self.rows = self.paginator.get_paginated_rows()
            except (InvalidPage, ValueError):
                raise Http404
        else:
            self.paginator = Paginator(table=self, django_paginator=None)
```

it seems that in lines 1467 and line 1460, Iommi Paginator is forced and things like:

```
class Paginator(IommiPaginator):
    template = 'lots/components/dt_paginator.html'

    attrs__class = {
        'pagination is-centered': True
    }
    container__attrs__class = {
        'pagination-list': True
    }


class BaseTable(Table):
    class Meta:
        member_class = Column
        attrs__class = {
            'table is-fullwidth is-hoverable thexo--lots-datatable': True
        }

    header__template = 'lots/components/dt_header_rows.html'
    model = Lot
    paginator = Paginator
```

seems to have no effect on the actual pagination html template rendering, it always falls back to the default bootstrap template, i still cant find how to acheive what i want in the documentation, maybe it is indeed possible im just not understading how...

i have also tried:

```
class BaseTable(Table):
    paginator__template = 'lots/components/dt_header_rows.html'
```

with no luck, same with:

```
class BaseTable(Table):
    paginator__call_target = 'path to my Paginator above'
```

i will greatly appreciate any help here!

**Comment by boxed** [comment]
I realized we hadn't released a version in a loooong time. I have now released 0.4.0 which contains a bunch of fixes for the paginator I made a while back. 

The correct syntax should be:

```
class BaseTable(Table):
    class Meta:
        paginator__template = 'lots/components/dt_header_rows.html'
```

Maybe better still is to define your own style and set it there:

```
my_style = Style(
    bootstrap,
    Paginator__template='lots/components/dt_header_rows.html'
)
register_style(my_style, 'my_style')
```

settings.py:
```
IOMMI_DEFAULT_STYLE='my_style'
```

Then you might not even need your BaseTable class.

**Comment by boxed** [comment]
Thanks for trying iommi btw! Great to see you getting up and running!

**Comment by sicksid** [comment]
thank you for answering man!

ill give this a try and ill also download the new version, so far im loving how great this project is!

**Comment by boxed** [comment]
Let me know if it works out!

**Comment by sicksid** [comment]
it worked! thank you!

**Comment by boxed** [comment]
Great! Please don't hesitate if you have further questions or opinions.
