### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by bgrundmann** [TriOptima/iommi#55]
Iommi currently seems to be english only.  See for example the builtin table query template.  Are there plans to change that?

**Comment by boxed** [comment]
It's on my todo list. But since we don't need it at work, and we have more pressing technical needs I haven't started it. I _think_ it could be fairly straight forward, but I have very little experience with this type of thing at all.

**Comment by boxed** [comment]
I decided to look at doing i18n for iommi, and then I got so far so quickly I decided to just complete it :P

In the linked commit I have added a translation for Swedish. We accept translations! :P
