### ISSUE TITLE
iommi and django's url.reverse

### ISSUE THREAD

**Issue by bgrundmann** [TriOptima/iommi#57]
This is more of a howto question than a issue as such.  So let me know if you would rather continue this on stackoverflow.

When using django I like to construct my url's using django's reverse function.  But with iommi and what I consider to be the obvious way to write the code the calls to those functions will happen too early resulting in the famous: django.core.exceptions.ImproperlyConfigured: The included URLconf '...' does not appear to have any patterns in it.

Concrete example:

```python
   class MyAppsNavBar(Menu):
        def item(name, url):
            return MenuItem(display_name=name, url=reverse(url))

        home = item('Home',  'myapp:index')
   
```

One can of course get around this kind of thing by wrapping each class in a function, and thereby effectively at each use case creating a separate class.

But while that seems fine'ish for something like a navbar, which we will only instantiate, It feels quite unnatural when talking about classes we will actually inhert from.  Say something like this does not work:

```python
class AppPageBase(Page):
  navbar = navbar()
  class Meta:
    title = "My App Title"

def index(request):
  class IndexPage(AppPageBase):
     body = ...

  return IndexPage()
````

and instead needs to be:

```python
def app_page_base():
  class AppPageBase(Page):
    navbar = navbar()
    class Meta:
      title = "My App Title"
  return AppPageBase

def index(request):
  class IndexPage(app_page_base()):
     body = ...

  return IndexPage()
````

Should I just get over this and do it like that?  Or what is the recommended iommi way?

**Comment by boxed** [comment]
There is a workaround which is

```python
   class MyAppsNavBar(Menu):
        def item(name, url):
            return MenuItem(display_name=name, url=lambda menu_item, **_: reverse(url))

        home = item('Home',  'myapp:index')
```

This has the obvious disadvantage of doing the `reverse()` call at each render over and over. Not quite as bad as creating the class over and over, but still not ideal. 

But I think in this case you just want `reverse_lazy`: https://docs.djangoproject.com/en/3.1/ref/urlresolvers/#reverse-lazy

**Comment by bgrundmann** [comment]
Ah that was actually what I tried before I the thunkified the class creation.  Sadly it results in this:

```python
...
  File "/usr/local/lib/python3.8/site-packages/iommi/evaluate.py", line 55, in evaluate
    return func_or_value(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/iommi/menu.py", line 107, in <lambda>
    regex=lambda menu_item, **_: '^' + menu_item.url if menu_item.url else None,

Exception Type: TypeError at /rentals/
Exception Value: can only concatenate str (not "__proxy__") to str

```

**Comment by boxed** [comment]
This was easy enough to fix. Thanks for the continued feedback, this is really gold!
