### ISSUE TITLE
Inconsistent handling of primary across styles and missing information in the API

### ISSUE THREAD

**Issue by bgrundmann** [TriOptima/iommi#76]
Currently the bulma and boostrap style disagree on when to mark buttons as primary.  Concretely the bulma style never and the bootstrap style always does.

This then means that switching between those two styles will realistically never have the same effect.

That said I believe the core reason actually comes from a lack of expressive power in the API.  That is not all buttons are primary buttons but the only button one can easily mark as not regular is the delete button (Action.delete).

How about introducing a Action.primary (with call_target_attribute=submit), and changing the styles to all only mark that one as primary?

Thoughts?

**Comment by boxed** [comment]
Yea, I guess that makes sense. First I was thinking this was a bit too specific to certain design systems, but looking at the design systems we support, and generally in GUIs it it seems like this concept of a primary button is pretty universal. 

As you said this shortcut would be pretty easy to add. We should also take care to change the default submit action on forms to be `Action.primary`.

**Comment by bgrundmann** [comment]
Great -- I'll give it a go.

**Comment by bgrundmann** [comment]
Done, see #77
