### ISSUE TITLE
bulk_queryset semantics seem odd

### ISSUE THREAD

**Issue by bgrundmann** [TriOptima/iommi#90]
https://github.com/TriOptima/iommi/blob/6c4790f1cbcacc2bda97c2a2fee8b925ad7f2bb8/iommi/table.py#L1875-L1882

Concretely if rows was initialized e.g like this: rows = Foo.objects.exclude(pk=42) and then the user selects all (i.e. _all_pks_ = 1) and say bulk delete the object with pk=42 will get deleted won't it?  (Unless the user also took care to set bulk_exclude accordingly but that seems far from obvious).

Actually the semantics seems even worse as when deleting everything the filters are not respected which seems clearly sub-optimal ...

If you agree than we could easily fix by starting with self.sorted_and_filtered_rows instead of model.objects.all() after my pull request #89 .

**Comment by bgrundmann** [comment]
I have no written tests.   I propose merging #89 first.  Then I'll do the minimal patch to fix bulk_queryset as per the last paragraph above.  And then we can merge #91 to ensure this doesn't happen again.

**Comment by boxed** [comment]
Fixed in de04820fb8aff677eaf9d12d6caf9528e6f2fc7d
